#  ____                _____                  
# |  _ \              / ____|                 
# | |_) |  ___ __  __| |      ___   _ __  ___ 
# |  _ <  / _ \\ \/ /| |     / _ \ | '__|/ _ \
# | |_) || (_) |>  < | |____| (_) || |  |  __/
# |____/  \___//_/\_\ \_____|\___/ |_|   \___|    
# Public PocketMine server core

name: BoxCore
author: BoxOfDevs
version: 1.0
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4]
main: BoxofDevs\BoxCore\main
description: "BoxCore: A Public Core plugin for PocketMine and Forks."
commands:
    lobby:
        description: "Go back to Lobby"
        aliases: [Lobby]
    home:
        description: "Go to your Home"
    ishome:
        description: "Check home"
    sethome:
        description: "Set your Home"